name = "cf-status"
type = "webpack"
workers_dev = true
account_id = "4e599df4216133509abaac54b109a647"

kv_namespaces = [
  { binding = "KV", id = "cd16d4566ec0408d84989e51f82488bc" }
]

[triggers]
crons = ["* * * * *"]

