name = "status-worker"
workers_dev = false
account_id = ""
compatibility_date = "2022-10-06"
main = "src/index.ts"

kv_namespaces = [
  { binding = "KV", id = "", preview_id = "" }
]

[triggers]
crons = ["* * * * *"]